services:
  db:
    image: mysql:8.0
    restart: always
    command: --init-file /data/application/init.sql
    volumes:
      - ./db:/data/application
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
